### PR TITLE
Delete branch

### LINKED ISSUE #5: User should be able to edit or delete own notes

### PR DESCRIPTION
**Pull request by alicia-mctc**
Please review thanks @JHughes9802 @haselfine @whagestad @jy8474np @quinzel25 @claraj

### CODE REVIEW

**Comment by whagestad** [comment]
Tested app locally, was able to add a note, then go in and edit it from my user profile. Was able to then delete the note using the delete button.

**Comment by whagestad** [comment]
Delete button did not give confirmation prompt when deleting from the app itself, but did get confirmation within the admin console.

**Comment by haselfine** [comment]
Functionality-wise, it works!

I said this over Zoom, but I'm just documenting here:

- When editing, your save button is also showing the text "edit" instead of "save"

- The formatting is a bit wonky. Try adding a < br > between the elements in the HTML. We can also update the CSS once it's merged. 

image

Finally, tests! Let me know if you need any help on those.

**Comment by jy8474np** [comment]
Conflicts resolved. Code fully-functional. Integrated with other Notes Model and Views.

**Pull request merged**
