### PR TITLE
Notes with Photos

### PR DESCRIPTION
**Pull request by jy8474np**
Notes updated with: add/delete photo, add/edit/delete notes, with updated pages and forms.
Again. lol

### CODE REVIEW

**Comment by jy8474np** [comment]
Link paths corrected. Code duplicating/overlapping with Alicia's assigned issues removed. Note titles linked from List page to Detail page for convenience/additional user engagement. Photo size width maxed at 500px for uniformity. Please review at your leisure. Thanks!

**Comment by quinzel25** [comment]
When clicking on the "See notes for this show and add your own" I'm receiving this error:

image

I'm not too sure why, it could be my computer since others have not been able to recreate this error

**Review by whagestad — COMMENTED** [review]
Was able to add notes w/ photos from admin console and have photos appear.
One issue: large photos are not resizing as intended

Issue adding photos from UI: note is created successfully, but the photo does not appear to upload.

**Review by haselfine — CHANGES_REQUESTED** [review]
When trying to add a photo in a new note through the UI, the new note posts, but no photo is added.

When adding a photo through the admin console, it successfully adds.

Check models.Note.save(). Maybe need some functionality in there for new photos.

**Comment by whagestad** [comment]
Works in testing locally, was able to add notes from UI and admin console, was able to view notes, pictures were present, images are resizing!!!

**Review by quinzel25 — APPROVED** [review]
Looks good! Could change posted date prompt to just a timestamp

**Review by whagestad — APPROVED** [review]
Approved

**Comment by alicia-mctc** [comment]
Great photos.

**Review by haselfine — APPROVED** [review]

**Pull request merged**
